# Generated by Django 5.1.4 on 2025-01-09 23:01

import datetime
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Windy', 'Windy'), ('Rainy', 'Rainy'), ('Snowy', 'Snowy'), ('Foggy', 'Foggy'), ('Cloudy', 'Cloudy'), ('Stormy', 'Stormy')], default='Sunny', max_length=20)),
                ('mood', multiselectfield.db.fields.MultiSelectField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('EXCITED', 'Excited'), ('FURIOUS', 'Furious'), ('DEPRESSED', 'Depressed'), ('EXHAUSTED', 'Exhausted'), ('FRIGHTENED', 'Frightened'), ('RELAXED', 'Relaxed'), ('SURPRISED', 'Surprised'), ('ANGRY', 'Angry'), ('NERVOUS', 'Nervous'), ('LONELY', 'Lonely'), ('JEALOUS', 'Jealous'), ('SHY', 'Shy'), ('UPSET', 'Upset'), ('DISGUSTED', 'Disgusted')], max_length=123)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
